defaultContentLanguage: zh-Hans
baseURL: "https://shaneyao.com"
params:
  displayFullLangName: true

theme: ["congo"]
module:
  mounts:
    
  - source: content/posts
    target: content/posts


markup:
  goldmark:
    renderer:
      unsafe: true